namespace:
  create: false

registry: k3d-finlab-registry:5000


frontend:
  image: finlab/frontend
  tag: "1.1.0"
  replicas: 2
  port: 80
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

postgres:
  enabled: true
  image: postgres:16-alpine
  user: finlab
  password: finlab
  db: finlab
  port: 5432
  storage: 1Gi

auth:
  image: finlab/auth
  tag: "1.1.0"
  replicas: 3
  port: 3001
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 6
    cpuUtilization: 70
  env:
    DATABASE_URL: "postgres://authuser:123456@postgres:5432/auth_db"

cart:
  image: finlab/cart
  tag: "1.1.0"
  replicas: 2
  port: 3002
  resources:
    requests:
      cpu: 150m
      memory: 128Mi
    limits:
      cpu: 400m
      memory: 256Mi
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 6
    cpuUtilization: 70
  env:
    DATABASE_URL: "postgres://cartserver:789875@postgres:5432/cart_db"

product:
  image: finlab/product
  tag: "1.1.0"
  replicas: 2
  port: 3003
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 6
    cpuUtilization: 70
  env:
    DATABASE_URL: "postgres://productuser:654321@postgres:5432/product_db"


#hpa:
  #enabled: true
  #minReplicas: 2
  #maxReplicas: 6
  #cpuUtilization: 70
